### ISSUE TITLE
Does adpbulk normalize for the number of cells per cluster

### ISSUE THREAD

**Issue by abhay1109** [noamteyssier/adpbulk#3]
Hi,

Thank you for publishing this package. I am using it to pseudobulk based on cluster annotations in scanpy. However, I'm still not sure how this package works. Does it simply add up the count values of all the cells in each cluster or does it subsample equal number of cells from each cluster? 

Best,
Abhay

**Comment by noamteyssier** [comment]
Hey Abhay,

it simply adds up the count values (or takes the mean) of all the cell-transcripts in each cluster. 

It doesn't subsample equal numbers of cells from each cluster.
